### ISSUE TITLE
type-coverage-core: Missing dependencies if using pnpm

### ISSUE THREAD

**Issue by unlight** [plantain-00/type-coverage#29]
#### Environment(if relevant):
pnpm package manager

#### Expected:
No error

#### Actual:
```
Error: Cannot find module 'minimatch'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (D:\Dev\node-package-starter\node_modules\.registry.npmjs.org\type-coverage-core\2.0.2_typescript@3.5.2\node_modules\type-coverage-core\dist\core.js:6:45)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
```

```
{
  "name": "type-coverage-core",
  "version": "2.0.2",
  "description": "A library to check type coverage for typescript code",
  "main": "dist/index.js",
  "types": "dist/index.d.ts",
  "repository": "https://github.com/plantain-00/type-coverage.git",
  "author": "york yao <yaoao12306@outlook.com>",
  "license": "MIT",
  "dependencies": {
    "glob": "7.1.4",
    "tslib": "1",
    "tsutils": "3"
  },
  "files": [
    "dist"
  ],
  "peerDependencies": {
    "typescript": "2 || 3"
  },
  "gitHead": "e3f7da37cb50d6fd93e04df8c3aac07d298ee030"
} 
```
Code:
```
Object.defineProperty(exports, "__esModule", { value: true });
const tslib_1 = require("tslib");
const typescript_1 = tslib_1.__importDefault(require("typescript"));
const path = tslib_1.__importStar(require("path"));
const minimatch_1 = tslib_1.__importDefault(require("minimatch")); // <----
const tsconfig_1 = require("./tsconfig");
const checker_1 = require("./checker");
const dependencies_1 = require("./dependencies");
const ignore_1 = require("./ignore");
const cache_1 = require("./cache");
```

**Comment by plantain-00** [comment]
`glob` has a dependency of `minimatch`: https://github.com/isaacs/node-glob/blob/master/package.json#L23
I just tried, it works with npm and yarn, It maybe a bug of pnpm
<img width="350" alt="屏幕快照 2019-06-24 17 13 30" src="https://user-images.githubusercontent.com/7639395/60006646-70ee1e80-96a3-11e9-95b6-ff7846afd189.png">

**Comment by plantain-00** [comment]
It seems there is a solution: https://pnpm.js.org/docs/en/faq.html#solution-3

**Comment by unlight** [comment]
That's the point. You must not use modules indirectly. What if next minor version will remove minimatch and replace by nanomatch, micromatch, etc.
But you still will reference to minimatch.
pnpm clearly says that it is bug of package.

> In most cases it means that one of the dependencies require packages not declared in package.json. It is a common mistake caused by flat node_modules. If this happens, this is an error in the dependency and the dependency should be fixed. That might take time though, so pnpm supports workarounds to make the **buggy packages** work.

**Comment by plantain-00** [comment]
v2.0.3 should fix this
